export interface LaTeXCompletion {
  label: string;
  displayLabel?: string;
  detail: string;
  type: "function" | "constant" | "keyword" | "environment";
  category?: string;
  snippet?: string;
}

export const latexCompletions: LaTeXCompletion[] = [
  // Greek Letters - Lowercase
  { label: "\\alpha", detail: "Greek letter α", type: "constant", category: "Greek" },
  { label: "\\beta", detail: "Greek letter β", type: "constant", category: "Greek" },
  { label: "\\gamma", detail: "Greek letter γ", type: "constant", category: "Greek" },
  { label: "\\delta", detail: "Greek letter δ", type: "constant", category: "Greek" },
  { label: "\\epsilon", detail: "Greek letter ε", type: "constant", category: "Greek" },
  { label: "\\varepsilon", detail: "Greek letter ε (variant)", type: "constant", category: "Greek" },
  { label: "\\zeta", detail: "Greek letter ζ", type: "constant", category: "Greek" },
  { label: "\\eta", detail: "Greek letter η", type: "constant", category: "Greek" },
  { label: "\\theta", detail: "Greek letter θ", type: "constant", category: "Greek" },
  { label: "\\vartheta", detail: "Greek letter θ (variant)", type: "constant", category: "Greek" },
  { label: "\\iota", detail: "Greek letter ι", type: "constant", category: "Greek" },
  { label: "\\kappa", detail: "Greek letter κ", type: "constant", category: "Greek" },
  { label: "\\lambda", detail: "Greek letter λ", type: "constant", category: "Greek" },
  { label: "\\mu", detail: "Greek letter μ", type: "constant", category: "Greek" },
  { label: "\\nu", detail: "Greek letter ν", type: "constant", category: "Greek" },
  { label: "\\xi", detail: "Greek letter ξ", type: "constant", category: "Greek" },
  { label: "\\pi", detail: "Greek letter π", type: "constant", category: "Greek" },
  { label: "\\varpi", detail: "Greek letter π (variant)", type: "constant", category: "Greek" },
  { label: "\\rho", detail: "Greek letter ρ", type: "constant", category: "Greek" },
  { label: "\\varrho", detail: "Greek letter ρ (variant)", type: "constant", category: "Greek" },
  { label: "\\sigma", detail: "Greek letter σ", type: "constant", category: "Greek" },
  { label: "\\varsigma", detail: "Greek letter ς (final)", type: "constant", category: "Greek" },
  { label: "\\tau", detail: "Greek letter τ", type: "constant", category: "Greek" },
  { label: "\\upsilon", detail: "Greek letter υ", type: "constant", category: "Greek" },
  { label: "\\phi", detail: "Greek letter φ", type: "constant", category: "Greek" },
  { label: "\\varphi", detail: "Greek letter φ (variant)", type: "constant", category: "Greek" },
  { label: "\\chi", detail: "Greek letter χ", type: "constant", category: "Greek" },
  { label: "\\psi", detail: "Greek letter ψ", type: "constant", category: "Greek" },
  { label: "\\omega", detail: "Greek letter ω", type: "constant", category: "Greek" },

  // Greek Letters - Uppercase
  { label: "\\Gamma", detail: "Greek letter Γ", type: "constant", category: "Greek" },
  { label: "\\Delta", detail: "Greek letter Δ", type: "constant", category: "Greek" },
  { label: "\\Theta", detail: "Greek letter Θ", type: "constant", category: "Greek" },
  { label: "\\Lambda", detail: "Greek letter Λ", type: "constant", category: "Greek" },
  { label: "\\Xi", detail: "Greek letter Ξ", type: "constant", category: "Greek" },
  { label: "\\Pi", detail: "Greek letter Π", type: "constant", category: "Greek" },
  { label: "\\Sigma", detail: "Greek letter Σ", type: "constant", category: "Greek" },
  { label: "\\Upsilon", detail: "Greek letter Υ", type: "constant", category: "Greek" },
  { label: "\\Phi", detail: "Greek letter Φ", type: "constant", category: "Greek" },
  { label: "\\Psi", detail: "Greek letter Ψ", type: "constant", category: "Greek" },
  { label: "\\Omega", detail: "Greek letter Ω", type: "constant", category: "Greek" },

  // Math Functions
  { label: "\\frac", displayLabel: "\\frac", detail: "Fraction", type: "function", category: "Math", snippet: "\\frac{#{}}#{}" },
  { label: "\\sqrt", displayLabel: "\\sqrt", detail: "Square root", type: "function", category: "Math", snippet: "\\sqrt{#{}}" },
  { label: "\\sum", displayLabel: "\\sum", detail: "Summation", type: "function", category: "Math", snippet: "\\sum_{#{}}" },
  { label: "\\int", displayLabel: "\\int", detail: "Integral", type: "function", category: "Math", snippet: "\\int_{#{}}" },
  { label: "\\prod", displayLabel: "\\prod", detail: "Product", type: "function", category: "Math", snippet: "\\prod_{#{}}" },
  { label: "\\lim", displayLabel: "\\lim", detail: "Limit", type: "function", category: "Math", snippet: "\\lim_{#{}}" },
  { label: "\\sin", detail: "Sine function", type: "function", category: "Math" },
  { label: "\\cos", detail: "Cosine function", type: "function", category: "Math" },
  { label: "\\tan", detail: "Tangent function", type: "function", category: "Math" },
  { label: "\\cot", detail: "Cotangent function", type: "function", category: "Math" },
  { label: "\\sec", detail: "Secant function", type: "function", category: "Math" },
  { label: "\\csc", detail: "Cosecant function", type: "function", category: "Math" },
  { label: "\\log", detail: "Logarithm", type: "function", category: "Math" },
  { label: "\\ln", detail: "Natural logarithm", type: "function", category: "Math" },
  { label: "\\exp", detail: "Exponential", type: "function", category: "Math" },
  { label: "\\max", detail: "Maximum", type: "function", category: "Math" },
  { label: "\\min", detail: "Minimum", type: "function", category: "Math" },
  { label: "\\sup", detail: "Supremum", type: "function", category: "Math" },
  { label: "\\inf", detail: "Infimum", type: "function", category: "Math" },

  // Binary Operators
  { label: "\\times", detail: "Multiplication ×", type: "constant", category: "Operators" },
  { label: "\\div", detail: "Division ÷", type: "constant", category: "Operators" },
  { label: "\\pm", detail: "Plus-minus ±", type: "constant", category: "Operators" },
  { label: "\\mp", detail: "Minus-plus ∓", type: "constant", category: "Operators" },
  { label: "\\cdot", detail: "Centered dot ·", type: "constant", category: "Operators" },
  { label: "\\ast", detail: "Asterisk *", type: "constant", category: "Operators" },
  { label: "\\star", detail: "Star ⋆", type: "constant", category: "Operators" },
  { label: "\\circ", detail: "Circle ∘", type: "constant", category: "Operators" },
  { label: "\\bullet", detail: "Bullet •", type: "constant", category: "Operators" },
  { label: "\\cap", detail: "Intersection ∩", type: "constant", category: "Operators" },
  { label: "\\cup", detail: "Union ∪", type: "constant", category: "Operators" },
  { label: "\\oplus", detail: "Circled plus ⊕", type: "constant", category: "Operators" },
  { label: "\\otimes", detail: "Circled times ⊗", type: "constant", category: "Operators" },
  { label: "\\wedge", detail: "Logical and ∧", type: "constant", category: "Operators" },
  { label: "\\vee", detail: "Logical or ∨", type: "constant", category: "Operators" },

  // Relations
  { label: "\\leq", detail: "Less than or equal ≤", type: "constant", category: "Relations" },
  { label: "\\geq", detail: "Greater than or equal ≥", type: "constant", category: "Relations" },
  { label: "\\neq", detail: "Not equal ≠", type: "constant", category: "Relations" },
  { label: "\\equiv", detail: "Equivalent ≡", type: "constant", category: "Relations" },
  { label: "\\approx", detail: "Approximately ≈", type: "constant", category: "Relations" },
  { label: "\\sim", detail: "Similar ~", type: "constant", category: "Relations" },
  { label: "\\simeq", detail: "Similar or equal ≃", type: "constant", category: "Relations" },
  { label: "\\cong", detail: "Congruent ≅", type: "constant", category: "Relations" },
  { label: "\\propto", detail: "Proportional ∝", type: "constant", category: "Relations" },
  { label: "\\ll", detail: "Much less than ≪", type: "constant", category: "Relations" },
  { label: "\\gg", detail: "Much greater than ≫", type: "constant", category: "Relations" },
  { label: "\\subset", detail: "Subset ⊂", type: "constant", category: "Relations" },
  { label: "\\supset", detail: "Superset ⊃", type: "constant", category: "Relations" },
  { label: "\\subseteq", detail: "Subset or equal ⊆", type: "constant", category: "Relations" },
  { label: "\\supseteq", detail: "Superset or equal ⊇", type: "constant", category: "Relations" },
  { label: "\\in", detail: "Element of ∈", type: "constant", category: "Relations" },
  { label: "\\notin", detail: "Not element of ∉", type: "constant", category: "Relations" },
  { label: "\\ni", detail: "Contains ∋", type: "constant", category: "Relations" },

  // Arrows
  { label: "\\rightarrow", detail: "Right arrow →", type: "constant", category: "Arrows" },
  { label: "\\leftarrow", detail: "Left arrow ←", type: "constant", category: "Arrows" },
  { label: "\\leftrightarrow", detail: "Left-right arrow ↔", type: "constant", category: "Arrows" },
  { label: "\\Rightarrow", detail: "Implies ⇒", type: "constant", category: "Arrows" },
  { label: "\\Leftarrow", detail: "Implied by ⇐", type: "constant", category: "Arrows" },
  { label: "\\Leftrightarrow", detail: "If and only if ⇔", type: "constant", category: "Arrows" },
  { label: "\\uparrow", detail: "Up arrow ↑", type: "constant", category: "Arrows" },
  { label: "\\downarrow", detail: "Down arrow ↓", type: "constant", category: "Arrows" },
  { label: "\\updownarrow", detail: "Up-down arrow ↕", type: "constant", category: "Arrows" },
  { label: "\\longrightarrow", detail: "Long right arrow ⟶", type: "constant", category: "Arrows" },
  { label: "\\longleftarrow", detail: "Long left arrow ⟵", type: "constant", category: "Arrows" },
  { label: "\\mapsto", detail: "Maps to ↦", type: "constant", category: "Arrows" },

  // Symbols
  { label: "\\infty", detail: "Infinity ∞", type: "constant", category: "Symbols" },
  { label: "\\partial", detail: "Partial derivative ∂", type: "constant", category: "Symbols" },
  { label: "\\nabla", detail: "Nabla/gradient ∇", type: "constant", category: "Symbols" },
  { label: "\\forall", detail: "For all ∀", type: "constant", category: "Symbols" },
  { label: "\\exists", detail: "Exists ∃", type: "constant", category: "Symbols" },
  { label: "\\nexists", detail: "Does not exist ∄", type: "constant", category: "Symbols" },
  { label: "\\emptyset", detail: "Empty set ∅", type: "constant", category: "Symbols" },
  { label: "\\varnothing", detail: "Empty set ∅ (variant)", type: "constant", category: "Symbols" },
  { label: "\\neg", detail: "Negation ¬", type: "constant", category: "Symbols" },
  { label: "\\angle", detail: "Angle ∠", type: "constant", category: "Symbols" },
  { label: "\\perp", detail: "Perpendicular ⊥", type: "constant", category: "Symbols" },
  { label: "\\parallel", detail: "Parallel ∥", type: "constant", category: "Symbols" },
  { label: "\\ell", detail: "Script l ℓ", type: "constant", category: "Symbols" },
  { label: "\\hbar", detail: "h-bar ℏ", type: "constant", category: "Symbols" },
  { label: "\\prime", detail: "Prime ′", type: "constant", category: "Symbols" },
  { label: "\\dag", detail: "Dagger †", type: "constant", category: "Symbols" },
  { label: "\\ddag", detail: "Double dagger ‡", type: "constant", category: "Symbols" },

  // Begin command
  { label: "\\begin", displayLabel: "\\begin", detail: "Begin environment", type: "keyword", category: "Environments" },

  // Environments
  { label: "\\begin{equation}", displayLabel: "equation", detail: "Numbered equation environment", type: "environment", category: "Environments", snippet: "\\begin{equation}\n\t#{}\n\\end{equation}" },
  { label: "\\begin{equation*}", displayLabel: "equation*", detail: "Unnumbered equation environment", type: "environment", category: "Environments", snippet: "\\begin{equation*}\n\t#{}\n\\end{equation*}" },
  { label: "\\begin{align}", displayLabel: "align", detail: "Aligned equations environment", type: "environment", category: "Environments", snippet: "\\begin{align}\n\t#{}\n\\end{align}" },
  { label: "\\begin{align*}", displayLabel: "align*", detail: "Unnumbered aligned equations", type: "environment", category: "Environments", snippet: "\\begin{align*}\n\t#{}\n\\end{align*}" },
  { label: "\\begin{matrix}", displayLabel: "matrix", detail: "Matrix (no brackets)", type: "environment", category: "Environments", snippet: "\\begin{matrix}\n\t#{}\n\\end{matrix}" },
  { label: "\\begin{pmatrix}", displayLabel: "pmatrix", detail: "Matrix with parentheses", type: "environment", category: "Environments", snippet: "\\begin{pmatrix}\n\t#{}\n\\end{pmatrix}" },
  { label: "\\begin{bmatrix}", displayLabel: "bmatrix", detail: "Matrix with brackets", type: "environment", category: "Environments", snippet: "\\begin{bmatrix}\n\t#{}\n\\end{bmatrix}" },
  { label: "\\begin{vmatrix}", displayLabel: "vmatrix", detail: "Determinant", type: "environment", category: "Environments", snippet: "\\begin{vmatrix}\n\t#{}\n\\end{vmatrix}" },
  { label: "\\begin{cases}", displayLabel: "cases", detail: "Cases (piecewise)", type: "environment", category: "Environments", snippet: "\\begin{cases}\n\t#{}\n\\end{cases}" },
  { label: "\\begin{split}", displayLabel: "split", detail: "Split equations", type: "environment", category: "Environments", snippet: "\\begin{split}\n\t#{}\n\\end{split}" },
  { label: "\\begin{gather}", displayLabel: "gather", detail: "Gathered equations", type: "environment", category: "Environments", snippet: "\\begin{gather}\n\t#{}\n\\end{gather}" },
  { label: "\\begin{itemize}", displayLabel: "itemize", detail: "Bullet list", type: "environment", category: "Environments", snippet: "\\begin{itemize}\n\t\\item #{}\n\\end{itemize}" },
  { label: "\\begin{enumerate}", displayLabel: "enumerate", detail: "Numbered list", type: "environment", category: "Environments", snippet: "\\begin{enumerate}\n\t\\item #{}\n\\end{enumerate}" },
  { label: "\\begin{figure}", displayLabel: "figure", detail: "Figure environment", type: "environment", category: "Environments", snippet: "\\begin{figure}\n\t#{}\n\\end{figure}" },
  { label: "\\begin{table}", displayLabel: "table", detail: "Table environment", type: "environment", category: "Environments", snippet: "\\begin{table}\n\t#{}\n\\end{table}" },
  { label: "\\begin{abstract}", displayLabel: "abstract", detail: "Abstract", type: "environment", category: "Environments", snippet: "\\begin{abstract}\n\t#{}\n\\end{abstract}" },

  // Text Formatting
  { label: "\\textbf", displayLabel: "\\textbf", detail: "Bold text", type: "function", category: "Formatting", snippet: "\\textbf{#{}}" },
  { label: "\\textit", displayLabel: "\\textit", detail: "Italic text", type: "function", category: "Formatting", snippet: "\\textit{#{}}" },
  { label: "\\texttt", displayLabel: "\\texttt", detail: "Typewriter text", type: "function", category: "Formatting", snippet: "\\texttt{#{}}" },
  { label: "\\textrm", displayLabel: "\\textrm", detail: "Roman text", type: "function", category: "Formatting", snippet: "\\textrm{#{}}" },
  { label: "\\textsf", displayLabel: "\\textsf", detail: "Sans-serif text", type: "function", category: "Formatting", snippet: "\\textsf{#{}}" },
  { label: "\\emph", displayLabel: "\\emph", detail: "Emphasized text", type: "function", category: "Formatting", snippet: "\\emph{#{}}" },
  { label: "\\underline", displayLabel: "\\underline", detail: "Underlined text", type: "function", category: "Formatting", snippet: "\\underline{#{}}" },
  { label: "\\text", displayLabel: "\\text", detail: "Text in math mode", type: "function", category: "Formatting", snippet: "\\text{#{}}" },
  { label: "\\mathbf", displayLabel: "\\mathbf", detail: "Bold math", type: "function", category: "Formatting", snippet: "\\mathbf{#{}}" },
  { label: "\\mathit", displayLabel: "\\mathit", detail: "Italic math", type: "function", category: "Formatting", snippet: "\\mathit{#{}}" },
  { label: "\\mathrm", displayLabel: "\\mathrm", detail: "Roman math", type: "function", category: "Formatting", snippet: "\\mathrm{#{}}" },
  { label: "\\mathcal", displayLabel: "\\mathcal", detail: "Calligraphic", type: "function", category: "Formatting", snippet: "\\mathcal{#{}}" },
  { label: "\\mathbb", displayLabel: "\\mathbb", detail: "Blackboard bold", type: "function", category: "Formatting", snippet: "\\mathbb{#{}}" },
  { label: "\\mathfrak", displayLabel: "\\mathfrak", detail: "Fraktur", type: "function", category: "Formatting", snippet: "\\mathfrak{#{}}" },

  // Delimiters
  { label: "\\left(", detail: "Auto-sized left parenthesis", type: "function", category: "Delimiters" },
  { label: "\\right)", detail: "Auto-sized right parenthesis", type: "function", category: "Delimiters" },
  { label: "\\left[", detail: "Auto-sized left bracket", type: "function", category: "Delimiters" },
  { label: "\\right]", detail: "Auto-sized right bracket", type: "function", category: "Delimiters" },
  { label: "\\left\\{", detail: "Auto-sized left brace", type: "function", category: "Delimiters" },
  { label: "\\right\\}", detail: "Auto-sized right brace", type: "function", category: "Delimiters" },
  { label: "\\left|", detail: "Auto-sized left bar", type: "function", category: "Delimiters" },
  { label: "\\right|", detail: "Auto-sized right bar", type: "function", category: "Delimiters" },
  { label: "\\langle", detail: "Left angle bracket ⟨", type: "constant", category: "Delimiters" },
  { label: "\\rangle", detail: "Right angle bracket ⟩", type: "constant", category: "Delimiters" },

  // Accents
  { label: "\\hat", displayLabel: "\\hat", detail: "Hat accent", type: "function", category: "Accents", snippet: "\\hat{#{}}" },
  { label: "\\tilde", displayLabel: "\\tilde", detail: "Tilde accent", type: "function", category: "Accents", snippet: "\\tilde{#{}}" },
  { label: "\\bar", displayLabel: "\\bar", detail: "Bar accent", type: "function", category: "Accents", snippet: "\\bar{#{}}" },
  { label: "\\vec", displayLabel: "\\vec", detail: "Vector arrow", type: "function", category: "Accents", snippet: "\\vec{#{}}" },
  { label: "\\dot", displayLabel: "\\dot", detail: "Dot accent", type: "function", category: "Accents", snippet: "\\dot{#{}}" },
  { label: "\\ddot", displayLabel: "\\ddot", detail: "Double dot", type: "function", category: "Accents", snippet: "\\ddot{#{}}" },
  { label: "\\acute", displayLabel: "\\acute", detail: "Acute accent", type: "function", category: "Accents", snippet: "\\acute{#{}}" },
  { label: "\\grave", displayLabel: "\\grave", detail: "Grave accent", type: "function", category: "Accents", snippet: "\\grave{#{}}" },
  { label: "\\check", displayLabel: "\\check", detail: "Check accent", type: "function", category: "Accents", snippet: "\\check{#{}}" },
  { label: "\\breve", displayLabel: "\\breve", detail: "Breve accent", type: "function", category: "Accents", snippet: "\\breve{#{}}" },

  // Document Structure
  { label: "\\section", displayLabel: "\\section", detail: "Section heading", type: "keyword", category: "Structure", snippet: "\\section{#{}}" },
  { label: "\\subsection", displayLabel: "\\subsection", detail: "Subsection heading", type: "keyword", category: "Structure", snippet: "\\subsection{#{}}" },
  { label: "\\subsubsection", displayLabel: "\\subsubsection", detail: "Subsubsection heading", type: "keyword", category: "Structure", snippet: "\\subsubsection{#{}}" },
  { label: "\\chapter", displayLabel: "\\chapter", detail: "Chapter heading", type: "keyword", category: "Structure", snippet: "\\chapter{#{}}" },
  { label: "\\part", displayLabel: "\\part", detail: "Part heading", type: "keyword", category: "Structure", snippet: "\\part{#{}}" },
  { label: "\\paragraph", displayLabel: "\\paragraph", detail: "Paragraph heading", type: "keyword", category: "Structure", snippet: "\\paragraph{#{}}" },
  { label: "\\subparagraph", displayLabel: "\\subparagraph", detail: "Subparagraph heading", type: "keyword", category: "Structure", snippet: "\\subparagraph{#{}}" },
  { label: "\\title", displayLabel: "\\title", detail: "Document title", type: "keyword", category: "Structure", snippet: "\\title{#{}}" },
  { label: "\\author", displayLabel: "\\author", detail: "Document author", type: "keyword", category: "Structure", snippet: "\\author{#{}}" },
  { label: "\\date", displayLabel: "\\date", detail: "Document date", type: "keyword", category: "Structure", snippet: "\\date{#{}}" },
  { label: "\\maketitle", detail: "Generate title", type: "keyword", category: "Structure" },
  { label: "\\tableofcontents", detail: "Table of contents", type: "keyword", category: "Structure" },

  // Spacing
  { label: "\\quad", detail: "Quad space (1em)", type: "constant", category: "Spacing" },
  { label: "\\qquad", detail: "Double quad space (2em)", type: "constant", category: "Spacing" },
  { label: "\\,", detail: "Thin space", type: "constant", category: "Spacing" },
  { label: "\\:", detail: "Medium space", type: "constant", category: "Spacing" },
  { label: "\\;", detail: "Thick space", type: "constant", category: "Spacing" },
  { label: "\\!", detail: "Negative thin space", type: "constant", category: "Spacing" },
  { label: "\\ ", detail: "Normal space", type: "constant", category: "Spacing" },
  { label: "\\hspace", displayLabel: "\\hspace", detail: "Horizontal space", type: "function", category: "Spacing", snippet: "\\hspace{#{}}" },
  { label: "\\vspace", displayLabel: "\\vspace", detail: "Vertical space", type: "function", category: "Spacing", snippet: "\\vspace{#{}}" },
  { label: "\\smallskip", detail: "Small vertical skip", type: "constant", category: "Spacing" },
  { label: "\\medskip", detail: "Medium vertical skip", type: "constant", category: "Spacing" },
  { label: "\\bigskip", detail: "Big vertical skip", type: "constant", category: "Spacing" },
  { label: "\\newline", detail: "Line break", type: "constant", category: "Spacing" },
  { label: "\\newpage", detail: "Page break", type: "constant", category: "Spacing" },
  { label: "\\noindent", detail: "No paragraph indent", type: "constant", category: "Spacing" },

  // References and Citations
  { label: "\\label", displayLabel: "\\label", detail: "Create label", type: "function", category: "References", snippet: "\\label{#{}}" },
  { label: "\\ref", displayLabel: "\\ref", detail: "Reference label", type: "function", category: "References", snippet: "\\ref{#{}}" },
  { label: "\\eqref", displayLabel: "\\eqref", detail: "Equation reference", type: "function", category: "References", snippet: "\\eqref{#{}}" },
  { label: "\\cite", displayLabel: "\\cite", detail: "Citation", type: "function", category: "References", snippet: "\\cite{#{}}" },
  { label: "\\footnote", displayLabel: "\\footnote", detail: "Footnote", type: "function", category: "References", snippet: "\\footnote{#{}}" },
  { label: "\\bibliography", displayLabel: "\\bibliography", detail: "Bibliography file", type: "function", category: "References", snippet: "\\bibliography{#{}}" },
  { label: "\\bibliographystyle", displayLabel: "\\bibliographystyle", detail: "Bibliography style", type: "function", category: "References", snippet: "\\bibliographystyle{#{}}" },

  // Special Characters
  { label: "\\&", detail: "Ampersand &", type: "constant", category: "Special" },
  { label: "\\%", detail: "Percent %", type: "constant", category: "Special" },
  { label: "\\$", detail: "Dollar $", type: "constant", category: "Special" },
  { label: "\\#", detail: "Hash #", type: "constant", category: "Special" },
  { label: "\\_", detail: "Underscore _", type: "constant", category: "Special" },
  { label: "\\{", detail: "Left brace {", type: "constant", category: "Special" },
  { label: "\\}", detail: "Right brace }", type: "constant", category: "Special" },
  { label: "\\~", displayLabel: "\\~", detail: "Tilde ~", type: "function", category: "Special", snippet: "\\~{#{}}" },
  { label: "\\^", displayLabel: "\\^", detail: "Caret ^", type: "function", category: "Special", snippet: "\\^{#{}}" },
  { label: "\\textbackslash", detail: "Backslash \\", type: "constant", category: "Special" },

  // Size Commands
  { label: "\\tiny", detail: "Tiny text size", type: "keyword", category: "Size" },
  { label: "\\scriptsize", detail: "Script text size", type: "keyword", category: "Size" },
  { label: "\\footnotesize", detail: "Footnote text size", type: "keyword", category: "Size" },
  { label: "\\small", detail: "Small text size", type: "keyword", category: "Size" },
  { label: "\\normalsize", detail: "Normal text size", type: "keyword", category: "Size" },
  { label: "\\large", detail: "Large text size", type: "keyword", category: "Size" },
  { label: "\\Large", detail: "Larger text size", type: "keyword", category: "Size" },
  { label: "\\LARGE", detail: "Even larger text size", type: "keyword", category: "Size" },
  { label: "\\huge", detail: "Huge text size", type: "keyword", category: "Size" },
  { label: "\\Huge", detail: "Largest text size", type: "keyword", category: "Size" },

  // Additional Math Symbols
  { label: "\\Re", detail: "Real part ℜ", type: "constant", category: "Math" },
  { label: "\\Im", detail: "Imaginary part ℑ", type: "constant", category: "Math" },
  { label: "\\aleph", detail: "Aleph ℵ", type: "constant", category: "Math" },
  { label: "\\wp", detail: "Weierstrass p ℘", type: "constant", category: "Math" },
  { label: "\\bot", detail: "Bottom ⊥", type: "constant", category: "Math" },
  { label: "\\top", detail: "Top ⊤", type: "constant", category: "Math" },
  { label: "\\triangle", detail: "Triangle △", type: "constant", category: "Math" },
  { label: "\\bigtriangleup", detail: "Big triangle up △", type: "constant", category: "Math" },
  { label: "\\bigtriangledown", detail: "Big triangle down ▽", type: "constant", category: "Math" },
  { label: "\\square", detail: "Square □", type: "constant", category: "Math" },
  { label: "\\diamond", detail: "Diamond ◇", type: "constant", category: "Math" },
  { label: "\\Box", detail: "Box □", type: "constant", category: "Math" },
  { label: "\\Diamond", detail: "Diamond ◇", type: "constant", category: "Math" },
  { label: "\\clubsuit", detail: "Club suit ♣", type: "constant", category: "Math" },
  { label: "\\diamondsuit", detail: "Diamond suit ♢", type: "constant", category: "Math" },
  { label: "\\heartsuit", detail: "Heart suit ♡", type: "constant", category: "Math" },
  { label: "\\spadesuit", detail: "Spade suit ♠", type: "constant", category: "Math" },

  // More Math Functions
  { label: "\\arcsin", detail: "Arcsine", type: "function", category: "Math" },
  { label: "\\arccos", detail: "Arccosine", type: "function", category: "Math" },
  { label: "\\arctan", detail: "Arctangent", type: "function", category: "Math" },
  { label: "\\sinh", detail: "Hyperbolic sine", type: "function", category: "Math" },
  { label: "\\cosh", detail: "Hyperbolic cosine", type: "function", category: "Math" },
  { label: "\\tanh", detail: "Hyperbolic tangent", type: "function", category: "Math" },
  { label: "\\coth", detail: "Hyperbolic cotangent", type: "function", category: "Math" },
  { label: "\\deg", detail: "Degree", type: "function", category: "Math" },
  { label: "\\det", detail: "Determinant", type: "function", category: "Math" },
  { label: "\\dim", detail: "Dimension", type: "function", category: "Math" },
  { label: "\\gcd", detail: "Greatest common divisor", type: "function", category: "Math" },
  { label: "\\ker", detail: "Kernel", type: "function", category: "Math" },
  { label: "\\arg", detail: "Argument", type: "function", category: "Math" },
  { label: "\\hom", detail: "Homomorphism", type: "function", category: "Math" },

  // Calculus
  { label: "\\oint", detail: "Contour integral", type: "function", category: "Calculus" },
  { label: "\\iint", detail: "Double integral", type: "function", category: "Calculus" },
  { label: "\\iiint", detail: "Triple integral", type: "function", category: "Calculus" },
  { label: "\\idotsint", detail: "Multiple integral", type: "function", category: "Calculus" },

  // Miscellaneous Commands
  { label: "\\dots", detail: "Ellipsis …", type: "constant", category: "Misc" },
  { label: "\\ldots", detail: "Low ellipsis …", type: "constant", category: "Misc" },
  { label: "\\cdots", detail: "Center ellipsis ⋯", type: "constant", category: "Misc" },
  { label: "\\vdots", detail: "Vertical ellipsis ⋮", type: "constant", category: "Misc" },
  { label: "\\ddots", detail: "Diagonal ellipsis ⋱", type: "constant", category: "Misc" },
  { label: "\\item", detail: "List item", type: "keyword", category: "Misc" },
  { label: "\\includegraphics", displayLabel: "\\includegraphics", detail: "Include image", type: "function", category: "Misc", snippet: "\\includegraphics[#{width}]{#{}}" },
  { label: "\\caption", displayLabel: "\\caption", detail: "Figure/table caption", type: "function", category: "Misc", snippet: "\\caption{#{}}" },
  { label: "\\href", displayLabel: "\\href", detail: "Hyperlink", type: "function", category: "Misc", snippet: "\\href{#{}}{{#{}}}" },
  { label: "\\url", displayLabel: "\\url", detail: "URL", type: "function", category: "Misc", snippet: "\\url{#{}}" },
  { label: "\\verb", displayLabel: "\\verb", detail: "Verbatim text", type: "function", category: "Misc", snippet: "\\verb|#{}|" },
  { label: "\\hline", detail: "Horizontal line in table", type: "constant", category: "Misc" },
  { label: "\\centering", detail: "Center content", type: "constant", category: "Misc" },
  { label: "\\textwidth", detail: "Text width dimension", type: "constant", category: "Misc" },
  { label: "\\linewidth", detail: "Line width dimension", type: "constant", category: "Misc" },
  { label: "\\newcommand", displayLabel: "\\newcommand", detail: "Define new command", type: "function", category: "Misc", snippet: "\\newcommand{#{}}{{#{}}}" },
  { label: "\\renewcommand", displayLabel: "\\renewcommand", detail: "Redefine command", type: "function", category: "Misc", snippet: "\\renewcommand{#{}}{{#{}}}" },
  { label: "\\multicolumn", displayLabel: "\\multicolumn", detail: "Span multiple columns", type: "function", category: "Misc", snippet: "\\multicolumn{#{}}{#{}}{#{}}" },
  { label: "\\setlength", displayLabel: "\\setlength", detail: "Set length", type: "function", category: "Misc", snippet: "\\setlength{#{}}{{#{}}}" },
  { label: "\\hfill", detail: "Horizontal fill", type: "constant", category: "Misc" },
  { label: "\\clearpage", detail: "Clear page", type: "constant", category: "Misc" },
  { label: "\\par", detail: "Paragraph break", type: "constant", category: "Misc" },
  { label: "\\LaTeX", detail: "LaTeX logo", type: "constant", category: "Misc" },
  { label: "\\TeX", detail: "TeX logo", type: "constant", category: "Misc" },
  { label: "\\boldsymbol", displayLabel: "\\boldsymbol", detail: "Bold symbol", type: "function", category: "Misc", snippet: "\\boldsymbol{#{}}" },
  { label: "\\newtheorem", displayLabel: "\\newtheorem", detail: "Define theorem environment", type: "function", category: "Misc", snippet: "\\newtheorem{#{}}{{#{}}}" },
  { label: "\\bibitem", displayLabel: "\\bibitem", detail: "Bibliography item", type: "function", category: "Misc", snippet: "\\bibitem{#{}}" },
  { label: "\\usepackage", displayLabel: "\\usepackage", detail: "Load package", type: "function", category: "Misc", snippet: "\\usepackage{#{}}" },
  { label: "\\documentclass", displayLabel: "\\documentclass", detail: "Document class", type: "function", category: "Misc", snippet: "\\documentclass{#{}}" },

  // Color (requires xcolor package)
  { label: "\\textcolor", displayLabel: "\\textcolor", detail: "Colored text", type: "function", category: "Color", snippet: "\\textcolor{#{}}{{#{}}}" },
  { label: "\\colorbox", displayLabel: "\\colorbox", detail: "Colored box", type: "function", category: "Color", snippet: "\\colorbox{#{}}{{#{}}}" },

  // AMS Math
  { label: "\\overset", displayLabel: "\\overset", detail: "Overset symbol", type: "function", category: "Math", snippet: "\\overset{#{}}{{#{}}}" },
  { label: "\\underset", displayLabel: "\\underset", detail: "Underset symbol", type: "function", category: "Math", snippet: "\\underset{#{}}{{#{}}}" },
  { label: "\\overbrace", displayLabel: "\\overbrace", detail: "Overbrace", type: "function", category: "Math", snippet: "\\overbrace{#{}}" },
  { label: "\\underbrace", displayLabel: "\\underbrace", detail: "Underbrace", type: "function", category: "Math", snippet: "\\underbrace{#{}}" },
  { label: "\\overline", displayLabel: "\\overline", detail: "Overline", type: "function", category: "Math", snippet: "\\overline{#{}}" },
  { label: "\\underline", displayLabel: "\\underline", detail: "Underline", type: "function", category: "Math", snippet: "\\underline{#{}}" },
  { label: "\\boxed", displayLabel: "\\boxed", detail: "Boxed expression", type: "function", category: "Math", snippet: "\\boxed{#{}}" },
];
