// This file contains all LaTeX completions from Overleaf
// Source: overleaf/services/web/frontend/js/features/source-editor/languages/latex/completions/data/top-hundred-snippets.ts

export interface LaTeXCompletion {
  label: string;
  displayLabel?: string;
  detail: string;
  type: "function" | "constant" | "keyword" | "environment";
  category?: string;
  snippet?: string;
}

export const overleafCompletions: LaTeXCompletion[] = [
  { label: "\\begin{}", detail: "Begin environment", type: "environment", snippet: "\\begin{#{}}" },
  { label: "\\end{}", detail: "End environment", type: "environment", snippet: "\\end{#{}}" },
  { label: "\\usepackage", detail: "Load package", type: "function", snippet: "\\usepackage[#{}]{#{}}" },
  { label: "\\item", detail: "List item", type: "function", snippet: "\\item " },
  { label: "\\section", detail: "Section heading", type: "function", snippet: "\\section{#{}}" },
  { label: "\\textbf", detail: "Bold text", type: "function", snippet: "\\textbf{#{}}" },
  { label: "\\cite", detail: "Citation", type: "function", snippet: "\\cite{#{}}" },
  { label: "\\label", detail: "Create label", type: "function", snippet: "\\label{#{}}" },
  { label: "\\textit", detail: "Italic text", type: "function", snippet: "\\textit{#{}}" },
  { label: "\\includegraphics", detail: "Include image", type: "function", snippet: "\\includegraphics[#{}]{#{}}" },
  { label: "\\documentclass", detail: "Document class", type: "function", snippet: "\\documentclass[#{}]{#{}}" },
  { label: "\\ref", detail: "Reference label", type: "keyword", snippet: "\\ref{#{}}" },
  { label: "\\frac", detail: "Fraction", type: "function", snippet: "\\frac{#{}}{#{}}" },
  { label: "\\subsection", detail: "Subsection heading", type: "function", snippet: "\\subsection{#{}}" },
  { label: "\\hline", detail: "Horizontal line in table", type: "function" },
  { label: "\\caption", detail: "Figure/table caption", type: "function", snippet: "\\caption{#{}}" },
  { label: "\\centering", detail: "Center content", type: "function" },
  { label: "\\vspace", detail: "Vertical space", type: "function", snippet: "\\vspace{#{}}" },
  { label: "\\title", detail: "Document title", type: "function", snippet: "\\title{#{}}" },
  { label: "\\author", detail: "Document author", type: "function", snippet: "\\author{#{}}" },
  { label: "\\maketitle", detail: "Generate title", type: "function" },
  { label: "\\textwidth", detail: "Text width dimension", type: "function" },
  { label: "\\newcommand", detail: "Define new command", type: "function", snippet: "\\newcommand{#{}}{#{}}" },
  { label: "\\date", detail: "Document date", type: "function", snippet: "\\date{#{}}" },
  { label: "\\emph", detail: "Emphasized text", type: "function", snippet: "\\emph{#{}}" },
  { label: "\\textsc", detail: "Small caps", type: "function", snippet: "\\textsc{#{}}" },
  { label: "\\multicolumn", detail: "Span multiple columns", type: "function", snippet: "\\multicolumn{#{}}{#{}}{#{}}" },
  { label: "\\input", detail: "Include file", type: "function", snippet: "\\input{#{}}" },
  { label: "\\alpha", detail: "Greek letter α", type: "function" },
  { label: "\\in", detail: "Element of ∈", type: "function" },
  { label: "\\mathbf", detail: "Bold math", type: "function", snippet: "\\mathbf{#{}}" },
  { label: "\\right", detail: "Right delimiter", type: "function" },
  { label: "\\left", detail: "Left delimiter", type: "function" },
  { label: "\\sum", detail: "Summation", type: "function" },
  { label: "\\chapter", detail: "Chapter heading", type: "function", snippet: "\\chapter{#{}}" },
  { label: "\\par", detail: "Paragraph break", type: "function" },
  { label: "\\lambda", detail: "Greek letter λ", type: "function" },
  { label: "\\subsubsection", detail: "Subsubsection heading", type: "function", snippet: "\\subsubsection{#{}}" },
  { label: "\\bibitem", detail: "Bibliography item", type: "function", snippet: "\\bibitem{#{}}" },
  { label: "\\text", detail: "Text in math mode", type: "function", snippet: "\\text{#{}}" },
  { label: "\\setlength", detail: "Set length", type: "function", snippet: "\\setlength{#{}}{#{}}" },
  { label: "\\mathcal", detail: "Calligraphic", type: "function", snippet: "\\mathcal{#{}}" },
  { label: "\\newpage", detail: "Page break", type: "function" },
  { label: "\\renewcommand", detail: "Redefine command", type: "function", snippet: "\\renewcommand{#{}}{#{}}" },
  { label: "\\theta", detail: "Greek letter θ", type: "function" },
  { label: "\\hspace", detail: "Horizontal space", type: "function", snippet: "\\hspace{#{}}" },
  { label: "\\beta", detail: "Greek letter β", type: "function" },
  { label: "\\texttt", detail: "Typewriter text", type: "function", snippet: "\\texttt{#{}}" },
  { label: "\\times", detail: "Multiplication ×", type: "function" },
  { label: "\\color", detail: "Set color", type: "function", snippet: "\\color{#{}}" },
  { label: "\\mu", detail: "Greek letter μ", type: "function" },
  { label: "\\bibliography", detail: "Bibliography file", type: "function", snippet: "\\bibliography{#{}}" },
  { label: "\\linewidth", detail: "Line width dimension", type: "function" },
  { label: "\\delta", detail: "Greek letter δ", type: "function" },
  { label: "\\sigma", detail: "Greek letter σ", type: "function" },
  { label: "\\pi", detail: "Greek letter π", type: "function" },
  { label: "\\hat", detail: "Hat accent", type: "function", snippet: "\\hat{#{}}" },
  { label: "\\bibliographystyle", detail: "Bibliography style", type: "function", snippet: "\\bibliographystyle{#{}}" },
  { label: "\\small", detail: "Small text size", type: "function" },
  { label: "\\LaTeX", detail: "LaTeX logo", type: "function" },
  { label: "\\cdot", detail: "Centered dot ·", type: "function" },
  { label: "\\footnote", detail: "Footnote", type: "function", snippet: "\\footnote{#{}}" },
  { label: "\\newtheorem", detail: "Define theorem environment", type: "function", snippet: "\\newtheorem{#{}}{#{}}" },
  { label: "\\Delta", detail: "Greek letter Δ", type: "function" },
  { label: "\\tau", detail: "Greek letter τ", type: "function" },
  { label: "\\hfill", detail: "Horizontal fill", type: "function" },
  { label: "\\leq", detail: "Less than or equal ≤", type: "function" },
  { label: "\\footnotesize", detail: "Footnote text size", type: "function" },
  { label: "\\large", detail: "Large text size", type: "function" },
  { label: "\\sqrt", detail: "Square root", type: "function", snippet: "\\sqrt{#{}}" },
  { label: "\\epsilon", detail: "Greek letter ε", type: "function" },
  { label: "\\Large", detail: "Large text size", type: "function" },
  { label: "\\rho", detail: "Greek letter ρ", type: "function" },
  { label: "\\omega", detail: "Greek letter ω", type: "function" },
  { label: "\\mathrm", detail: "Roman math", type: "function", snippet: "\\mathrm{#{}}" },
  { label: "\\boldsymbol", detail: "Bold symbol", type: "function", snippet: "\\boldsymbol{#{}}" },
  { label: "\\gamma", detail: "Greek letter γ", type: "function" },
  { label: "\\clearpage", detail: "Clear page", type: "function" },
  { label: "\\infty", detail: "Infinity ∞", type: "function" },
  { label: "\\phi", detail: "Greek letter φ", type: "function" },
  { label: "\\partial", detail: "Partial derivative ∂", type: "function" },
  { label: "\\include", detail: "Include file", type: "function", snippet: "\\include{#{}}" },
  { label: "\\address", detail: "Address", type: "function", snippet: "\\address{#{}}" },
  { label: "\\quad", detail: "Quad space", type: "function" },
  { label: "\\paragraph", detail: "Paragraph heading", type: "function", snippet: "\\paragraph{#{}}" },
  { label: "\\varepsilon", detail: "Greek letter ε (variant)", type: "function" },
  { label: "\\zeta", detail: "Greek letter ζ", type: "function" },
  { label: "\\eta", detail: "Greek letter η", type: "function" },
  { label: "\\vartheta", detail: "Greek letter θ (variant)", type: "function" },
  { label: "\\iota", detail: "Greek letter ι", type: "function" },
  { label: "\\kappa", detail: "Greek letter κ", type: "function" },
  { label: "\\nu", detail: "Greek letter ν", type: "function" },
  { label: "\\xi", detail: "Greek letter ξ", type: "function" },
  { label: "\\varpi", detail: "Greek letter π (variant)", type: "function" },
  { label: "\\varrho", detail: "Greek letter ρ (variant)", type: "function" },
  { label: "\\varsigma", detail: "Greek letter ς (final)", type: "function" },
  { label: "\\upsilon", detail: "Greek letter υ", type: "function" },
  { label: "\\varphi", detail: "Greek letter φ (variant)", type: "function" },
  { label: "\\chi", detail: "Greek letter χ", type: "function" },
  { label: "\\psi", detail: "Greek letter ψ", type: "function" },
  { label: "\\Gamma", detail: "Greek letter Γ", type: "function" },
  { label: "\\Theta", detail: "Greek letter Θ", type: "function" },
  { label: "\\Lambda", detail: "Greek letter Λ", type: "function" },
  { label: "\\Xi", detail: "Greek letter Ξ", type: "function" },
  { label: "\\Pi", detail: "Greek letter Π", type: "function" },
  { label: "\\Sigma", detail: "Greek letter Σ", type: "function" },
  { label: "\\Upsilon", detail: "Greek letter Υ", type: "function" },
  { label: "\\Phi", detail: "Greek letter Φ", type: "function" },
  { label: "\\Psi", detail: "Greek letter Ψ", type: "function" },
  { label: "\\Omega", detail: "Greek letter Ω", type: "function" },
];
